---
services:
  daemon:
    build: .
    ports:
    - 0.0.0.0:8484:8484
    init: true
    command: ['rebuilderd', '-v', '-c', '/config/rebuilderd.conf']
    environment:
    - REBUILDERD_COOKIE_PATH=/secret/auth
    - RUST_LOG=debug
    volumes:
    - ./secret:/secret
    - ./data2:/data
    - ./data2/rebuilderd.conf:/config/rebuilderd.conf:ro
    - ./data2/rebuilderd-stats.conf:/etc/rebuilderd-stats.conf:ro
