#!/bin/sh

# PROVIDE: rebuilderd_worker
# REQUIRE: LOGIN DAEMON NETWORKING
# KEYWORD: shutdown

# Add to /usr/local/etc/rc.d/rebuilderd_worker
# chmod +x /usr/local/etc/rc.d/rebuilderd_worker
# service rebuilderd_worker start
# tail -f /var/log/rebuilderd_worker.log

# Add the following lines to /etc/rc.conf to enable rebuilderd_worker:
#
# rebuilderd_worker_enable="YES"
#
# Optional configuration:
# rebuilderd_worker_conf="/usr/local/etc/rebuilderd-worker.conf"
# rebuilderd_worker_user="root"        # user to run as (needs root for rebuilder backends)
# rebuilderd_worker_name="worker1"     # worker name (defaults to hostname)

. /etc/rc.subr

name="rebuilderd_worker"
rcvar="${name}_enable"
procname="/home/freebsd/rebuilderd/target/debug/rebuilderd-worker"

load_rc_config $name

: "${rebuilderd_worker_enable:=NO}"
: "${rebuilderd_worker_conf:=/usr/local/etc/rebuilderd-worker.conf}"
: "${rebuilderd_worker_user:=root}"
: "${rebuilderd_worker_name:=$(hostname -s)}"

pidfile="/var/run/${name}.pid"
logfile="/var/log/${name}.log"

command="/usr/sbin/daemon"
command_args="-f -o ${logfile} -p ${pidfile} -u ${rebuilderd_worker_user} ${procname} -c ${rebuilderd_worker_conf} -n ${rebuilderd_worker_name} connect"

start_precmd="${name}_prestart"

rebuilderd_worker_prestart()
{
    # Check if config file exists
    if [ ! -f "${rebuilderd_worker_conf}" ]; then
        warn "Configuration file ${rebuilderd_worker_conf} does not exist"
        return 1
    fi

    # Create pidfile directory if it doesn't exist
    install -d -o root -g wheel -m 0755 /var/run
}

run_rc_command "$@"
